// Code generated by goctl. DO NOT EDIT!
// Source: add.proto

package server

import (
	"context"

	"bookstore/rpc/add/internal/logic"
	"bookstore/rpc/add/internal/svc"
	"bookstore/rpc/add/pb/pb"
)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) Add(ctx context.Context, in *pb.AddReq) (*pb.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
